corrected tagging pipeline + updated README

diff --git a/.github/workflows/training.yml b/.github/workflows/training.yml
--- a/.github/workflows/training.yml
+++ b/.github/workflows/training.yml
@@ -33,14 +33,14 @@ jobs:
         python llm-tagging.py
         python filter-faults.py
         python train.py
-    - name: List tags folder
-      run: ls -R tags || echo "tags folder not found"
+    - name: List data folder
+      run: ls -R data || echo "data folder not found"
     - name: Commit and Push Changes
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add tags
-        git commit -m "Add tags generated by script"
+        git add data
+        git commit -m "LLM-generated tags uploaded"
         git push
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
